server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user

hystrix:
  shareSecurityContext: true